# Generated by Django 4.0.3 on 2022-09-30 07:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ID', models.CharField(db_index=True, default='SOME STRING', max_length=100, unique=True)),
                ('birth_date', models.DateField(null=True)),
                ('date_left', models.DateField(null=True)),
                ('left', models.BooleanField(default=False)),
                ('phone_number', models.CharField(default='SOME STRING', max_length=100)),
                ('position', models.CharField(choices=[('MS', 'Master'), ('CA', 'Cashier'), ('CL', 'Clerk')], default='CL', max_length=2)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
