# Generated by Django 4.0.3 on 2022-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ID', models.CharField(db_index=True, default='SOME STRING', max_length=100, unique=True)),
                ('first_name', models.CharField(default='SOME STRING', max_length=100)),
                ('last_name', models.CharField(default='SOME STRING', max_length=100)),
                ('birth_date', models.DateField(null=True)),
                ('date_joined', models.DateField(null=True)),
                ('date_left', models.DateField(null=True)),
                ('left', models.BooleanField(default=False)),
                ('email', models.EmailField(default='SOME@STRING', max_length=254)),
                ('phone_number', models.CharField(default='SOME STRING', max_length=100)),
                ('position', models.CharField(choices=[('MS', 'Master'), ('CA', 'Cashier'), ('CL', 'Clerk')], default='CL', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
