# Generated by Django 4.0.3 on 2022-08-09 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('admin_ID', models.CharField(db_index=True, default='SOME STRING', max_length=100, unique=True)),
                ('admin_first_name', models.CharField(default='SOME STRING', max_length=100)),
                ('admin_last_name', models.CharField(default='SOME STRING', max_length=100)),
                ('admin_birth_date', models.DateField(null=True)),
                ('admin_date_joined', models.DateField(null=True)),
                ('admin_date_left', models.DateField(null=True)),
                ('admin_left', models.BooleanField(default=False)),
                ('admin_email', models.EmailField(default='SOME@STRING', max_length=254)),
                ('admin_phone_number', models.CharField(default='SOME STRING', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='position',
            name='pos',
            field=models.CharField(default='کتابدار', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libraryadmin',
            name='admin_position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='management.position'),
        ),
    ]
