# Generated by Django 4.0.3 on 2022-08-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_libraryadmin_delete_admin_position_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryadmin',
            name='admin_position',
            field=models.CharField(choices=[('MS', 'Master'), ('CA', 'CASHIER'), ('CL', 'Clerk')], default='CL', max_length=2),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
