# Generated by Django 4.0.3 on 2022-08-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_libraryadmin_admin_position_delete_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryadmin',
            name='admin_position',
            field=models.CharField(choices=[('MS', 'Master'), ('CA', 'Cashier'), ('CL', 'Clerk')], default='CL', max_length=2),
        ),
    ]
