# Generated by Django 4.0.3 on 2022-08-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_libraryadmin_admin_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryadmin',
            name='admin_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
