# Generated by Django 4.0.3 on 2022-08-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_libraryadmin_admin_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryadmin',
            old_name='admin_ID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='libraryadmin',
            old_name='admin_birth_date',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='libraryadmin',
            old_name='admin_date_joined',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='libraryadmin',
            old_name='admin_date_left',
            new_name='date_left',
        ),
        migrations.RenameField(
            model_name='libraryadmin',
            old_name='admin_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='libraryadmin',
            old_name='admin_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='libraryadmin',
            old_name='admin_is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='libraryadmin',
            old_name='admin_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='libraryadmin',
            old_name='admin_left',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='libraryadmin',
            old_name='admin_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='libraryadmin',
            old_name='admin_position',
            new_name='position',
        ),
    ]
