version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=WZ4xt133iDjF0m6seMR7tRD-WU8uT-hA

  web:
    build: .
    command: sh -c "python3 manage.py runserver 0.0.0.0:8080 && python3 manage.py migrate"
    ports:
      - "8080:8080"
    volumes:
      - .:/code

    depends_on:
      - db
      - redis
      
  redis:
    image: redis:alpine



  celery_worker:
    build:
      context: .

    image: celery_worker
    command: bash -c "celery -A library worker -l INFO"

    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - web

  celery_beat:
      build:
        context: .

      image: celery_beat
      command: bash -c "celery -A library beat -l INFO"
      env_file:
        - ./.env

      volumes:
      - .:/code

      depends_on:
        - redis
        - db
        - web

