version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=JvPFW1-6UBqsmu1jh1qTdV7qV4Pk3bta

  web:
    build: .
    command: python3 manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code

    depends_on:
      - db
  redis:
    image: redis:alpine



  celery_worker:
    build:
      context: .

    image: celery_worker
    command: celery -A library worker -l INFO

    volumes:
      - .:/library
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - web

  celery_beat:
      build:
        context: .

      image: celery_beat
      command: celery -A library beat -l INFO
      env_file:
        - ./.env

      volumes:
      - .:/library

      depends_on:
        - redis
        - db
        - web

