# Generated by Django 4.0.3 on 2022-09-07 07:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_submitted', models.DateTimeField(null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('end_rent', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LoanBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.bookobject')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(null=True)),
                ('book_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.bookobject')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
