# Generated by Django 4.0.3 on 2022-08-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='date_submitted',
            field=models.DateTimeField(null=True),
        ),
    ]
