# Generated by Django 4.0.3 on 2022-10-08 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookobject_company'),
        ('core', '0002_alter_loanbook_loan_alter_loanmodel_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbook',
            name='book_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_obj', to='book.bookobject'),
        ),
    ]
