# Generated by Django 4.0.3 on 2022-08-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookobject_available_alter_bookclass_quantity'),
        ('customer', '0001_initial'),
        ('core', '0002_loan_date_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(null=True)),
                ('book_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.bookobject')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
