# Generated by Django 4.0.3 on 2022-08-02 06:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_email_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='signincode',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 6, 21, 25, 535859, tzinfo=utc), verbose_name='expiration time (of ad)'),
        ),
    ]
