# Generated by Django 4.0.3 on 2022-08-04 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_signincode_expirationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signincode',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 43, 44, 524191, tzinfo=utc), verbose_name='expiration time (of ad)'),
        ),
    ]
