# Generated by Django 4.0.3 on 2022-08-04 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_signincode_expirationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signincode',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 2, 27, 48, 841400), verbose_name='expiration time (of ad)'),
        ),
    ]
