# Generated by Django 4.0.3 on 2022-08-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_signincode_expirationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signincode',
            name='expirationTime',
            field=models.DateTimeField(),
        ),
    ]
