# Generated by Django 4.0.3 on 2022-09-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('authors', models.TextField(null=True)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=102, unique=True)),
                ('date_published', models.DateField(default=None)),
                ('published_no', models.SmallIntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
                ('book_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.bookclass')),
            ],
        ),
        migrations.AddField(
            model_name='bookclass',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.bookgenre'),
        ),
    ]
