# Generated by Django 4.0.3 on 2022-09-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images')),
                ('book_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookobject')),
            ],
        ),
    ]
