# Generated by Django 4.0.3 on 2022-08-22 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookclass_name_alter_bookclass_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclass',
            name='slug',
        ),
        migrations.AlterField(
            model_name='bookobject',
            name='book_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.bookclass'),
        ),
    ]
