# Generated by Django 4.0.3 on 2022-09-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='book_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_image', to='book.bookobject'),
        ),
    ]
