# Generated by Django 4.0.3 on 2022-08-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_bookclass_slug_alter_bookobject_book_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookobject',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookclass',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
