# Generated by Django 4.0.3 on 2022-09-30 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('book', '0003_alter_bookimage_book_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookobject',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
