# Generated by Django 4.0.3 on 2022-11-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookobject_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookobject',
            name='book_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_class_company', to='book.bookclass'),
        ),
    ]
