# Generated by Django 4.0.3 on 2022-11-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_bookobject_book_class_alter_bookobject_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookclass',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='bookclass',
            name='date_created',
            field=models.DateField(default=None, null=True),
        ),
    ]
