# Generated by Django 4.0.3 on 2022-11-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_bookclass_options_bookclass_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookclass',
            options={},
        ),
    ]
