# Generated by Django 4.0.3 on 2022-11-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_bookclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookclass',
            options={'ordering': ['-date_created']},
        ),
    ]
