# Generated by Django 4.0.3 on 2022-11-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_bookclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookclass',
            options={},
        ),
    ]
