# Generated by Django 4.0.3 on 2022-12-03 08:40

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_bookclass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclass',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 500], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 500], upload_to='images'),
        ),
    ]
