# Generated by Django 4.0.3 on 2022-12-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_bookclass_image_alter_bookimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclass',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookgenre'),
        ),
        migrations.AlterField(
            model_name='bookobject',
            name='book_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_class', to='book.bookclass'),
        ),
    ]
