# Generated by Django 4.0.3 on 2022-09-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('province', models.CharField(db_index=True, max_length=100)),
                ('phone_num', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
